AllCops:
  Exclude:
    - 'bin/*'
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
