module Jotter
  VERSION: String

  class CLI
    def help: -> untyped

    def new: (String note) -> untyped

    def version: -> untyped

    def self.exit_on_failure?: -> bool

    def self.start: -> untyped
  end

  self.@root: Pathname

  def self.new: (String note, String root) -> int

  def self.setup: -> untyped

  def self.version: -> int

  private

  def self.log_exception: (Symbol | nil method_name, String message, StandardError exp) -> untyped

  def self.log_message: (Symbol | nil method_name, String message) -> untyped

  def self.note_name: (String note) -> String

  def self.path_name: (String name) -> Pathname

  def self.section: -> String

  def self.title: (String name) -> String

  def self.update_file?: (Pathname file, String mode, String data) -> bool
end
